import { NextResponse } from "next/server";
import { calculateRestaurantAvailableSlots } from "@/lib/restaurant-slots";

export const dynamic = "force-dynamic";

type RouteContext = {
  params: Promise<{
    id: string;
  }>;
};

type AvailableSlot = {
  time?: string;
  label?: string;
  startTime: string;
  endTime: string;
  availableTables: unknown[];
};

type AvailableSlotsResult = {
  success?: boolean;
  message?: string;
  slots?: AvailableSlot[];
  [key: string]: unknown;
};

function parseGuestCount(value: unknown) {
  const guestCount = Number(value);

  if (!Number.isInteger(guestCount) || guestCount < 1) {
    return null;
  }

  return guestCount;
}

function normalizeText(value: unknown) {
  return String(value || "").trim();
}

function normalizeOptionalId(value: unknown) {
  const normalizedValue = normalizeText(value);

  if (
    !normalizedValue ||
    normalizedValue === "null" ||
    normalizedValue === "undefined" ||
    normalizedValue === "ALL"
  ) {
    return null;
  }

  return normalizedValue;
}

function normalizeTime(value: unknown) {
  const normalizedValue = normalizeText(value);

  if (!normalizedValue) {
    return "";
  }

  const twentyFourHourMatch =
    /^(\d{1,2}):([0-5]\d)(?::[0-5]\d)?$/.exec(normalizedValue);

  if (twentyFourHourMatch) {
    const hours = Number(twentyFourHourMatch[1]);
    const minutes = twentyFourHourMatch[2];

    if (hours < 0 || hours > 23) {
      return normalizedValue;
    }

    return `${String(hours).padStart(2, "0")}:${minutes}`;
  }

  const twelveHourMatch =
    /^(\d{1,2}):([0-5]\d)\s*(AM|PM)$/i.exec(normalizedValue);

  if (twelveHourMatch) {
    let hours = Number(twelveHourMatch[1]);
    const minutes = twelveHourMatch[2];
    const period = twelveHourMatch[3].toUpperCase();

    if (hours < 1 || hours > 12) {
      return normalizedValue;
    }

    if (period === "PM" && hours < 12) {
      hours += 12;
    }

    if (period === "AM" && hours === 12) {
      hours = 0;
    }

    return `${String(hours).padStart(2, "0")}:${minutes}`;
  }

  return normalizedValue;
}

function filterSlotsBySelectedTime(
  result: AvailableSlotsResult,
  startTime: string
): AvailableSlotsResult {
  /*
   * Preserve validation and availability errors returned by the
   * main slot calculation function.
   *
   * Without this check, an actual backend error could be replaced
   * with a successful response containing an empty slot array.
   */
  if (result.success === false) {
    return result;
  }

  const normalizedStartTime = normalizeTime(startTime);

  /*
   * When no specific start time is provided, return every available
   * slot generated by the reservation slot calculator.
   */
  if (!normalizedStartTime) {
    return result;
  }

  const slots = Array.isArray(result.slots) ? result.slots : [];

  const filteredSlots = slots.filter((slot) => {
    const slotStartTime = normalizeTime(
      slot.startTime || slot.time
    );

    return slotStartTime === normalizedStartTime;
  });

  if (filteredSlots.length === 0) {
    return {
      ...result,
      success: true,
      message:
        "No table is available for the selected date, time, and guest count.",
      slots: [],
    };
  }

  return {
    ...result,
    success: true,
    message: "Available tables loaded successfully.",
    slots: filteredSlots,
  };
}

async function getAvailableSlotsResponse({
  restaurantId,
  date,
  guestCount,
  tableId,
  startTime,
}: {
  restaurantId: string;
  date: string;
  guestCount: number;
  tableId: string | null;
  startTime: string;
}) {
  const result = await calculateRestaurantAvailableSlots({
    restaurantId,
    date,
    guestCount,
    tableId,
  });

  return filterSlotsBySelectedTime(
    result as AvailableSlotsResult,
    startTime
  );
}

export async function GET(
  request: Request,
  { params }: RouteContext
) {
  try {
    const { id } = await params;
    const { searchParams } = new URL(request.url);

    const restaurantId = normalizeText(id);
    const date = normalizeText(searchParams.get("date"));
    const guestCount = parseGuestCount(
      searchParams.get("guestCount")
    );
    const tableId = normalizeOptionalId(
      searchParams.get("tableId")
    );
    const startTime = normalizeTime(
      searchParams.get("startTime")
    );

    if (!restaurantId) {
      return NextResponse.json(
        {
          success: false,
          message: "Restaurant ID is required.",
          slots: [],
        },
        {
          status: 400,
        }
      );
    }

    if (!date) {
      return NextResponse.json(
        {
          success: false,
          message: "Reservation date is required.",
          slots: [],
        },
        {
          status: 400,
        }
      );
    }

    if (!guestCount) {
      return NextResponse.json(
        {
          success: false,
          message: "Guest count must be at least 1.",
          slots: [],
        },
        {
          status: 400,
        }
      );
    }

    const result = await getAvailableSlotsResponse({
      restaurantId,
      date,
      guestCount,
      tableId,
      startTime,
    });

    return NextResponse.json(result);
  } catch (error) {
    console.error(
      "AVAILABLE_RESTAURANT_SLOTS_GET_ERROR",
      error
    );

    return NextResponse.json(
      {
        success: false,
        message:
          "Unable to load available reservation slots.",
        slots: [],
      },
      {
        status: 500,
      }
    );
  }
}

export async function POST(
  request: Request,
  { params }: RouteContext
) {
  try {
    const { id } = await params;

    const body = (await request
      .json()
      .catch(() => null)) as Record<string, unknown> | null;

    const restaurantId = normalizeText(id);
    const date = normalizeText(body?.date);
    const guestCount = parseGuestCount(body?.guestCount);
    const tableId = normalizeOptionalId(body?.tableId);
    const startTime = normalizeTime(body?.startTime);

    if (!restaurantId) {
      return NextResponse.json(
        {
          success: false,
          message: "Restaurant ID is required.",
          slots: [],
        },
        {
          status: 400,
        }
      );
    }

    if (!date) {
      return NextResponse.json(
        {
          success: false,
          message: "Reservation date is required.",
          slots: [],
        },
        {
          status: 400,
        }
      );
    }

    if (!guestCount) {
      return NextResponse.json(
        {
          success: false,
          message: "Guest count must be at least 1.",
          slots: [],
        },
        {
          status: 400,
        }
      );
    }

    const result = await getAvailableSlotsResponse({
      restaurantId,
      date,
      guestCount,
      tableId,
      startTime,
    });

    return NextResponse.json(result);
  } catch (error) {
    console.error(
      "AVAILABLE_RESTAURANT_SLOTS_POST_ERROR",
      error
    );

    return NextResponse.json(
      {
        success: false,
        message:
          "Unable to load available reservation slots.",
        slots: [],
      },
      {
        status: 500,
      }
    );
  }
}